### ISSUE TITLE
Bug when I try cifar100

### ISSUE THREAD

**Issue by heng-yin** [gaopengcuhk/Tip-Adapter#1]
Thanks for your work.
When I try your code on CIFAR100, I got this error and I dont know how to slove it.
Due to ImageNet's huge number of images, I can only do this.
PLS help.

`Torch version: 1.7.1
Namespace(alpha=1, augment_epoch=10, beta=1.17, lr=0.001, train_epoch=20)
Model parameters: 151,277,313
Input resolution: 224
Context length: 77
Vocab size: 49408
Load data finished.
start getting text features.
finish getting text features. start getting image features
start saving training image features
Augment time: 0 / 10
  3%|▉                               | 6/196 [00:03<01:45,  1.81it/s]
Traceback (most recent call last):
  File "main.py", line 487, in <module>
    main()
  File "main.py", line 244, in main
    for i, (images, target) in enumerate(tqdm(train_loader)):
  File "/home/yh/.conda/envs/prompt/lib/python3.6/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/yh/.conda/envs/prompt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/yh/.conda/envs/prompt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/yh/.conda/envs/prompt/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yh/.conda/envs/prompt/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yh/.conda/envs/prompt/lib/python3.6/site-packages/torchvision/datasets/cifar.py", line 113, in __getitem__
    img, target = self.data[index], self.targets[index]
IndexError: list index out of range
[1]+  Killed                  python main.py`

**Comment by gaopengcuhk** [comment]
We will add scripts for new datasets in a few weeks. Stay tuned.

**Comment by ZrrSkywalker** [comment]
@heng-yin Thanks for your great patience!
We have release the code for other datasets in the repo. Maybe you can follow their configs to implement on CIFAR100.
