### ISSUE TITLE
Any future plan to add support for microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224?

### ISSUE THREAD

**Issue by 0x6f6f** [gaopengcuhk/Tip-Adapter#25]
Current CLIP model seems to be lack of knowledge about medical images, so introduce more pre-trained CLIP models may extend the project's scope of application.

**Comment by caoziyang1997** [comment]
为什么imagenet数据集跑不起来，报错：
Traceback (most recent call last):
File "main_imagenet.py", line 186, in
main()
File "main_imagenet.py", line 150, in main
imagenet = ImageNet(cfg['root_path'], cfg['shots'], preprocess)
File "/root/zhaojia/Tip-Adapter/datasets/imagenet.py", line 203, in init
self.train = torchvision.datasets.ImageNet(self.image_dir, split='train', transform=train_preprocess)
File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/imagenet.py", line 55, in init
self.parse_archives()
File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/imagenet.py", line 70, in parse_archives
parse_devkit_archive(self.root)
File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/imagenet.py", line 149, in parse_devkit_archive
_verify_archive(root, file, md5)
File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/imagenet.py", line 103, in _verify_archive
raise RuntimeError(msg.format(file, root))
RuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted. You need to download it externally and place it in imagenet/images.
